name: Build Vue
on: [push]
jobs:
  build-and-deploy:
    runs-on: ${{ fromJSON('["ubuntu-latest", "self-hosted"]')[github.repository == 'github/docs-internal'] }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: npm

      - name: Install
        run: |
          cd node
          npm ci

      - name: Build
        run: |
          cd node
          npm run build
        env:
          BASE_URL: https://${{ vars.GH_PAGES_CNAME }}/

      - name: Push to Github Pages
        run: |
          cd node/dist
          ln -s index.html 404.html
          echo '${{ vars.GH_PAGES_CNAME }}' > CNAME
          git config --global user.email "${{ vars.GH_EMAIL }}"
          git config --global user.name "${{ vars.GH_NAME }}"
          git init
          git add -A
          git commit -m 'Deployment.'
          git push -f https://${{ vars.GH_USERNAME }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ vars.GH_PUSH_REPO }}.git master:gh-pages

